# n.b. whenprotobuf version changes, it must be update in three places in this
# file (no macros or variables in YAML).

language: python
python:
  - "2.7"

cache:
    directories:
    - /tmp/proto3.2.0
before_install:
    - sudo apt-get update -qq
    - bash tools/travis-install-protoc.sh 3.2.0
    - export PATH=/tmp/proto3.2.0/bin:$PATH
    - pip install -r requirements.txt
script:
    - cwltool
